#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HELPSMobileFrontEnd.Resource", IsApplication=true)]

namespace HELPSMobileFrontEnd
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonRoundedCorners = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditTextRounded = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LoginButtonGradient = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RectangleRounded = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060043
			public const int NameText = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int NotesText = 2131099716;
			
			// aapt resource value: 0x7f060031
			public const int birth = 2131099697;
			
			// aapt resource value: 0x7f06002b
			public const int btnCourse = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int btnEducation = 2131099692;
			
			// aapt resource value: 0x7f060023
			public const int btnHelp = 2131099683;
			
			// aapt resource value: 0x7f06000e
			public const int btnLogin = 2131099662;
			
			// aapt resource value: 0x7f060025
			public const int btnLogout = 2131099685;
			
			// aapt resource value: 0x7f06001c
			public const int btnMakeBooking = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int btnMarkAttendance = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int btnProfile = 2131099682;
			
			// aapt resource value: 0x7f060020
			public const int btnSearch = 2131099680;
			
			// aapt resource value: 0x7f06001d
			public const int btnViewBooking = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int ctlExListBox = 2131099651;
			
			// aapt resource value: 0x7f060040
			public const int ddlcountry = 2131099712;
			
			// aapt resource value: 0x7f06003e
			public const int ddllanguage = 2131099710;
			
			// aapt resource value: 0x7f060000
			public const int elvCurrentBookings = 2131099648;
			
			// aapt resource value: 0x7f060027
			public const int elvExListBox = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int elvPastBookings = 2131099688;
			
			// aapt resource value: 0x7f060036
			public const int female = 2131099702;
			
			// aapt resource value: 0x7f06003d
			public const int firstlanguage = 2131099709;
			
			// aapt resource value: 0x7f060024
			public const int flLogout = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int flNoCurrentBookings = 2131099649;
			
			// aapt resource value: 0x7f060029
			public const int flNoPastBookings = 2131099689;
			
			// aapt resource value: 0x7f06000d
			public const int flSignIn = 2131099661;
			
			// aapt resource value: 0x7f060047
			public const int flTabs = 2131099719;
			
			// aapt resource value: 0x7f060005
			public const int frameLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060033
			public const int gender = 2131099699;
			
			// aapt resource value: 0x7f06003b
			public const int international = 2131099707;
			
			// aapt resource value: 0x7f06002e
			public const int lblFirstName = 2131099694;
			
			// aapt resource value: 0x7f06003f
			public const int lblStudentEmail = 2131099711;
			
			// aapt resource value: 0x7f060032
			public const int lbldateofbirth = 2131099698;
			
			// aapt resource value: 0x7f060004
			public const int llFAQChild = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int llPageRoot = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int llRoot = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int llTextFields = 2131099658;
			
			// aapt resource value: 0x7f060042
			public const int lstItemTask = 2131099714;
			
			// aapt resource value: 0x7f060008
			public const int lvClasses = 2131099656;
			
			// aapt resource value: 0x7f060026
			public const int lvWorkShops = 2131099686;
			
			// aapt resource value: 0x7f060035
			public const int male = 2131099701;
			
			// aapt resource value: 0x7f06002f
			public const int name = 2131099695;
			
			// aapt resource value: 0x7f060037
			public const int number = 2131099703;
			
			// aapt resource value: 0x7f06003a
			public const int permanent = 2131099706;
			
			// aapt resource value: 0x7f060034
			public const int radioGroup1 = 2131099700;
			
			// aapt resource value: 0x7f06003c
			public const int relativeLayout4 = 2131099708;
			
			// aapt resource value: 0x7f060011
			public const int rowBackground = 2131099665;
			
			// aapt resource value: 0x7f06001b
			public const int rowButtons1 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int rowButtons2 = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int rowButtons3 = 2131099681;
			
			// aapt resource value: 0x7f060015
			public const int rowDescription = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int rowNextSession = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int rowTimeRoom = 2131099671;
			
			// aapt resource value: 0x7f060045
			public const int sliding_tabs = 2131099717;
			
			// aapt resource value: 0x7f060039
			public const int status = 2131099705;
			
			// aapt resource value: 0x7f06002d
			public const int studentName = 2131099693;
			
			// aapt resource value: 0x7f06000c
			public const int tbPassword = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int tbStudentID = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int tlBackgroundBorder = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int tlButtons = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int tlNextSession = 2131099666;
			
			// aapt resource value: 0x7f060041
			public const int tvListLayout = 2131099713;
			
			// aapt resource value: 0x7f060002
			public const int tvNoCurrentBookings = 2131099650;
			
			// aapt resource value: 0x7f06002a
			public const int tvNoPastBookings = 2131099690;
			
			// aapt resource value: 0x7f060016
			public const int txtDescription = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int txtLarge = 2131099655;
			
			// aapt resource value: 0x7f060030
			public const int txtName = 2131099696;
			
			// aapt resource value: 0x7f060014
			public const int txtNextSession = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int txtRoom = 2131099673;
			
			// aapt resource value: 0x7f060006
			public const int txtSmall = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int txtTime = 2131099672;
			
			// aapt resource value: 0x7f060038
			public const int txtcontactnumber = 2131099704;
			
			// aapt resource value: 0x7f060046
			public const int viewpager = 2131099718;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CurrentBookings = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HelpPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListControl_Child = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListControl_Group = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListSessions = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainMenu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MakeBookingList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MakeBookingSesh = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MarkAttendance = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PastBookings = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Profile = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SessionsListViewLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int TaskListItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ViewBookingFragmentLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ViewBookings = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040002
			public const int ActionBarTheme = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int ActionBarTitleStyle = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int MainButton = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int MyActionBar = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int TableLayoutInfo = 2130968577;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
